name: Build JOSS Paper PDF

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build-paper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc curl

    - name: Install tectonic manually
      run: |
        curl -L https://github.com/tectonic-typesetting/tectonic/releases/download/tectonic%400.14.1/tectonic-0.14.1-x86_64-unknown-linux-musl.tar.gz \
          -o tectonic.tar.gz
        tar -xzf tectonic.tar.gz
        sudo mv tectonic /usr/local/bin/

    - name: Download JOSS LaTeX template
      run: |
        mkdir -p joss-latex
        curl -L https://raw.githubusercontent.com/openjournals/joss/main/latex/joss.cls -o joss-latex/joss.cls
        curl -L https://raw.githubusercontent.com/openjournals/joss/main/latex/template.tex -o joss-latex/template.tex

    - name: Build paper.pdf with JOSS formatting
      run: |
        pandoc paper.md \
          --from markdown \
          --output paper.pdf \
          --pdf-engine=tectonic \
          --citeproc \
          --template=joss-latex/template.tex \
          --bibliography=paper.bib \
          -V classoption=twocolumn \
          -V geometry:margin=1in

    - name: Upload paper.pdf
      uses: actions/upload-artifact@v4
      with:
        name: joss-paper-pdf
        path: paper.pdf
