name: Build JOSS Paper

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install jupyter jupytext
          pip install -r requirements.txt || true  # Optional

      - name: Build JOSS paper PDF
        uses: openjournals/joss-paper-action@v1
        with:
          paper-path: paper.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: joss-paper-pdf
          path: paper.pdf
