name: Docs Doctest CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  doctest:
    name: Run Sphinx doctests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install package (editable)
        run: pip install -e .

      - name: Install documentation + test dependencies
        run: |
          pip install sphinx
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true  # optional

      - name: Run Sphinx doctests
        working-directory: docs
        run: |
          sphinx-build -b doctest . _build/doctest
