name: Documentation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  doctests:
    name: Sphinx Doctests (RST)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true
          pip install sphinx

      - name: Run Sphinx doctests
        run: |
          sphinx-build -b doctest docs/source docs/_build/doctest

  docstring-tests:
    name: Docstring Tests (Python)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -e .
          pip install -r requirements.txt
          pip install -r requirements-dev.txt || true
          pip install pytest

      - name: Install HiGHS
        run: sudo apt install -y coinor-cbc

      - name: Run docstring tests
        run: |
          pytest --doctest-modules txgraffiti
