name: Python CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install txgraffiti2 in editable mode
        run: pip install -e .

      - name: Install test dependencies
        run: pip install pytest

      - name: Run pytest
        run: PYTHONPATH=. pytest -vv --maxfail=1 --disable-warnings
