name: Python CI

# Run on every push to branches and on PRs
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.13]

    steps:
      # 1) Check out your code
      - uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # 4) Run pytest
      - name: Run pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # (Optional) 5) Upload coverage to Codecov
      # - name: Generate coverage report
      #   run: |
      #     pip install pytest-cov
      #     pytest --cov=txgraffiti2 --cov-report=xml
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v3
      #   with:
      #     file: ./coverage.xml
